// db/clinic.js
// -----------------------------------------------------------------------
// Clinic Workflow System (Phase 1): staff roles, patient intake, doctor
// queue, digital prescriptions, medicine master, and billing.
// All tables are ADDITIVE — existing appointments/reviews are untouched.
// -----------------------------------------------------------------------
const bcrypt = require('bcryptjs');
const { pool } = require('./database');

// ============================= SCHEMA =============================
async function initClinicDb() {
  // Persistent binary storage for images (doctor photo, staff photos) —
  // stored IN the database so they survive Render/Railway redeploys,
  // instead of the local filesystem which resets on free tiers.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS clinic_assets (
      key         TEXT PRIMARY KEY,
      data        BYTEA NOT NULL,
      mime_type   TEXT NOT NULL,
      updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS staff_users (
      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username       TEXT UNIQUE NOT NULL,
      password_hash  TEXT NOT NULL,
      role           TEXT NOT NULL CHECK (role IN ('doctor','reception','billing')),
      active         BOOLEAN NOT NULL DEFAULT true,
      created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS staff_profiles (
      staff_user_id        BIGINT PRIMARY KEY REFERENCES staff_users(id) ON DELETE CASCADE,
      full_name            TEXT,
      age                  INTEGER,
      mobile               TEXT,
      address              TEXT,
      registration_number  TEXT,
      photo_data           BYTEA,
      photo_mime           TEXT,
      updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS patients (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name  TEXT NOT NULL,
      last_name   TEXT,
      phone       TEXT NOT NULL,
      gender      TEXT,
      dob         TEXT,
      age         INTEGER,
      address     TEXT,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_patients_phone ON patients(phone);`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS visits (
      id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      patient_id        BIGINT NOT NULL REFERENCES patients(id),
      bp                TEXT,
      temperature       TEXT,
      pulse             TEXT,
      weight            TEXT,
      chief_complaint   TEXT,
      notes             TEXT,
      status            TEXT NOT NULL DEFAULT 'waiting',
      created_by        BIGINT REFERENCES staff_users(id),
      doctor_id         BIGINT REFERENCES staff_users(id),
      created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_visits_status ON visits(status);`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_visits_patient ON visits(patient_id);`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS medicines (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        TEXT NOT NULL,
      strength    TEXT,
      price       NUMERIC(10,2),
      category    TEXT,
      active      BOOLEAN NOT NULL DEFAULT true,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_medicines_name ON medicines(name);`);

  // additive migration: inventory fields for existing medicines table
  await pool.query(`ALTER TABLE medicines ADD COLUMN IF NOT EXISTS stock_quantity INTEGER;`);
  await pool.query(`ALTER TABLE medicines ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER NOT NULL DEFAULT 10;`);
  await pool.query(`ALTER TABLE medicines ADD COLUMN IF NOT EXISTS expiry_date DATE;`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS prescriptions (
      id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visit_id                 BIGINT NOT NULL REFERENCES visits(id),
      doctor_id                BIGINT REFERENCES staff_users(id),
      mode                     TEXT NOT NULL DEFAULT 'digital',
      chief_complaint          TEXT,
      examination              TEXT,
      diagnosis                TEXT,
      procedure_notes          TEXT,
      advice                   TEXT,
      investigation            TEXT,
      prognosis                TEXT,
      findings                 TEXT,
      doctor_notes             TEXT,
      emergency_instructions   TEXT,
      follow_up                TEXT,
      created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_prescriptions_visit ON prescriptions(visit_id);`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS prescription_medicines (
      id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      prescription_id   BIGINT NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
      medicine_id       BIGINT REFERENCES medicines(id),
      medicine_name     TEXT NOT NULL,
      dosage            TEXT,
      instructions      TEXT,
      quantity          INTEGER NOT NULL DEFAULT 1,
      price             NUMERIC(10,2)
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS quick_type_suggestions (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      section      TEXT NOT NULL,
      text         TEXT NOT NULL,
      created_by   BIGINT REFERENCES staff_users(id),
      created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_quicktype_section ON quick_type_suggestions(section);`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS bills (
      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visit_id       BIGINT NOT NULL REFERENCES visits(id),
      bill_number    TEXT UNIQUE NOT NULL,
      patient_name   TEXT NOT NULL,
      patient_phone  TEXT NOT NULL,
      doctor_name    TEXT,
      subtotal       NUMERIC(10,2) NOT NULL DEFAULT 0,
      discount       NUMERIC(10,2) NOT NULL DEFAULT 0,
      grand_total    NUMERIC(10,2) NOT NULL DEFAULT 0,
      created_by     BIGINT REFERENCES staff_users(id),
      created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS bill_items (
      id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      bill_id        BIGINT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
      medicine_name  TEXT NOT NULL,
      quantity       INTEGER NOT NULL DEFAULT 1,
      unit_price     NUMERIC(10,2) NOT NULL DEFAULT 0,
      line_total     NUMERIC(10,2) NOT NULL DEFAULT 0
    );
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS prescription_photos (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visit_id     BIGINT NOT NULL REFERENCES visits(id),
      data         BYTEA NOT NULL,
      mime_type    TEXT NOT NULL,
      uploaded_by  BIGINT REFERENCES staff_users(id),
      uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_prescription_photos_visit ON prescription_photos(visit_id);`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS visit_attachments (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      visit_id     BIGINT NOT NULL REFERENCES visits(id),
      filename     TEXT NOT NULL,
      data         BYTEA NOT NULL,
      mime_type    TEXT NOT NULL,
      uploaded_by  BIGINT REFERENCES staff_users(id),
      uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_attachments_visit ON visit_attachments(visit_id);`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS audit_log (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      staff_id    BIGINT REFERENCES staff_users(id),
      role        TEXT,
      action      TEXT NOT NULL,
      details     TEXT,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at DESC);`);

  // ---- clinic_settings: simple key/value store (consulting fee, etc.) ----
  await pool.query(`
    CREATE TABLE IF NOT EXISTS clinic_settings (
      key         TEXT PRIMARY KEY,
      value       TEXT,
      updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);
  await pool.query(`
    INSERT INTO clinic_settings (key, value) VALUES ('consulting_fee', '0')
    ON CONFLICT (key) DO NOTHING;
  `);

  // additive: bill_items needs medicine_id so stock can be auto-deducted on billing
  await pool.query(`ALTER TABLE bill_items ADD COLUMN IF NOT EXISTS medicine_id BIGINT REFERENCES medicines(id);`);

  // additive: bills need a consulting fee line + a "history retained" status marker
  await pool.query(`ALTER TABLE bills ADD COLUMN IF NOT EXISTS consulting_fee NUMERIC(10,2) NOT NULL DEFAULT 0;`);

  // one-time data fix: correct the doctor's name if it was seeded/saved before the spelling fix
  await pool.query(`
    UPDATE staff_profiles SET full_name = 'Dr. Alok Kushwaha', updated_at = now()
    WHERE full_name = 'Dr. Aalok Kushwaha';
  `);

  // allow deleting a staff account without blocking on history —
  // historical visits/bills/etc. stay intact, just with no staff link
  const staffFkFixes = [
    ['visits', 'created_by'],
    ['visits', 'doctor_id'],
    ['prescriptions', 'doctor_id'],
    ['quick_type_suggestions', 'created_by'],
    ['bills', 'created_by'],
    ['visit_attachments', 'uploaded_by'],
    ['prescription_photos', 'uploaded_by'],
    ['audit_log', 'staff_id'],
  ];
  for (const [table, column] of staffFkFixes) {
    const constraintName = `${table}_${column}_fkey`;
    await pool.query(`ALTER TABLE ${table} DROP CONSTRAINT IF EXISTS ${constraintName};`);
    await pool.query(
      `ALTER TABLE ${table} ADD CONSTRAINT ${constraintName}
       FOREIGN KEY (${column}) REFERENCES staff_users(id) ON DELETE SET NULL;`
    );
  }

  await seedDefaults();
  console.log('  ✓ Clinic workflow schema ready (staff, patients, visits, prescriptions, medicines, bills)');
}

// Seed a default account per role + a few starter Quick Type suggestions,
// ONLY if none exist yet — never overwrites real data.
async function seedDefaults() {
  const { rows } = await pool.query(`SELECT COUNT(*)::int AS c FROM staff_users`);
  if (rows[0].c === 0) {
    const defaults = [
      { username: 'doctor', password: 'doctor123', role: 'doctor', name: 'Dr. Alok Kushwaha' },
      { username: 'reception', password: 'reception123', role: 'reception', name: 'Reception Staff' },
      { username: 'billing', password: 'billing123', role: 'billing', name: 'Billing Staff' },
    ];
    for (const d of defaults) {
      const hash = bcrypt.hashSync(d.password, 10);
      const { rows: userRows } = await pool.query(
        `INSERT INTO staff_users (username, password_hash, role) VALUES ($1, $2, $3) RETURNING id`,
        [d.username, hash, d.role]
      );
      await pool.query(
        `INSERT INTO staff_profiles (staff_user_id, full_name) VALUES ($1, $2)`,
        [userRows[0].id, d.name]
      );
    }
    console.log('  ✓ Seeded default staff accounts (doctor/doctor123, reception/reception123, billing/billing123) — CHANGE THESE PASSWORDS');
  }

  const { rows: qtRows } = await pool.query(`SELECT COUNT(*)::int AS c FROM quick_type_suggestions`);
  if (qtRows[0].c === 0) {
    const defaultSuggestions = {
      chief_complaint: ['Fever', 'Headache', 'Cold & Cough', 'Body ache', 'Stomach ache', 'Joint pain'],
      examination: ['Normal', 'Mild tenderness', 'No abnormality detected', 'Throat congested'],
      diagnosis: ['Viral fever', 'Acute gastritis', 'Allergic rhinitis', 'Migraine'],
      advice: ['Plenty of fluids', 'Rest for 2-3 days', 'Light diet', 'Avoid cold food/drinks'],
      investigation: ['CBC', 'Blood sugar (fasting)', 'Urine routine', 'Not required'],
      follow_up: ['After 3 days', 'After 1 week', 'SOS (if needed)', 'After 2 weeks'],
    };
    for (const [section, items] of Object.entries(defaultSuggestions)) {
      for (const text of items) {
        await pool.query(
          `INSERT INTO quick_type_suggestions (section, text) VALUES ($1, $2)`,
          [section, text]
        );
      }
    }
  }
}

// ============================= STAFF =============================
async function getStaffByUsername(username, role) {
  const { rows } = await pool.query(
    `SELECT su.*, sp.full_name, sp.age, sp.mobile, sp.address, sp.registration_number, sp.updated_at AS profile_updated_at
     FROM staff_users su LEFT JOIN staff_profiles sp ON sp.staff_user_id = su.id
     WHERE su.username = $1 AND su.role = $2 AND su.active = true`,
    [username, role]
  );
  return rows[0] || null;
}

async function getStaffById(id) {
  const { rows } = await pool.query(
    `SELECT su.*, sp.full_name, sp.age, sp.mobile, sp.address, sp.registration_number
     FROM staff_users su LEFT JOIN staff_profiles sp ON sp.staff_user_id = su.id
     WHERE su.id = $1`,
    [id]
  );
  return rows[0] || null;
}

async function listStaff() {
  const { rows } = await pool.query(
    `SELECT su.id, su.username, su.role, su.active, su.created_at, sp.full_name, sp.mobile
     FROM staff_users su LEFT JOIN staff_profiles sp ON sp.staff_user_id = su.id
     ORDER BY su.role, su.username`
  );
  return rows;
}

async function createStaff({ username, password, role }) {
  const hash = bcrypt.hashSync(password, 10);
  const { rows } = await pool.query(
    `INSERT INTO staff_users (username, password_hash, role) VALUES ($1, $2, $3) RETURNING id, username, role, active, created_at`,
    [username, hash, role]
  );
  await pool.query(`INSERT INTO staff_profiles (staff_user_id) VALUES ($1)`, [rows[0].id]);
  return rows[0];
}

async function setStaffActive(id, active) {
  await pool.query(`UPDATE staff_users SET active = $1 WHERE id = $2`, [active, id]);
}

async function deleteStaff(id) {
  await pool.query(`DELETE FROM staff_users WHERE id = $1`, [id]);
}

async function updateStaffProfile(staffUserId, { full_name, age, mobile, address, registration_number }) {
  await pool.query(
    `UPDATE staff_profiles
     SET full_name = $1, age = $2, mobile = $3, address = $4, registration_number = $5, updated_at = now()
     WHERE staff_user_id = $6`,
    [full_name || null, age || null, mobile || null, address || null, registration_number || null, staffUserId]
  );
  return getStaffById(staffUserId);
}

async function updateStaffPhoto(staffUserId, buffer, mimeType) {
  await pool.query(
    `UPDATE staff_profiles SET photo_data = $1, photo_mime = $2, updated_at = now() WHERE staff_user_id = $3`,
    [buffer, mimeType, staffUserId]
  );
}

async function getStaffPhoto(staffUserId) {
  const { rows } = await pool.query(
    `SELECT photo_data, photo_mime FROM staff_profiles WHERE staff_user_id = $1`,
    [staffUserId]
  );
  return rows[0] && rows[0].photo_data ? rows[0] : null;
}

// ============================= CLINIC ASSETS (persistent doctor photo) =============================
async function setClinicAsset(key, buffer, mimeType) {
  await pool.query(
    `INSERT INTO clinic_assets (key, data, mime_type, updated_at) VALUES ($1, $2, $3, now())
     ON CONFLICT (key) DO UPDATE SET data = $2, mime_type = $3, updated_at = now()`,
    [key, buffer, mimeType]
  );
}

async function getClinicAsset(key) {
  const { rows } = await pool.query(`SELECT data, mime_type, updated_at FROM clinic_assets WHERE key = $1`, [key]);
  return rows[0] || null;
}

// ============================= PATIENTS =============================
async function findPatientsByPhone(phone) {
  const { rows } = await pool.query(
    `SELECT * FROM patients WHERE phone = $1 ORDER BY created_at DESC`,
    [phone.trim()]
  );
  return rows;
}

async function searchPatients(search) {
  const { rows } = await pool.query(
    `SELECT * FROM patients WHERE phone ILIKE $1 OR first_name ILIKE $1 OR last_name ILIKE $1
     ORDER BY created_at DESC LIMIT 20`,
    [`%${search}%`]
  );
  return rows;
}

async function createPatient(data) {
  const { rows } = await pool.query(
    `INSERT INTO patients (first_name, last_name, phone, gender, dob, age, address)
     VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *`,
    [data.first_name, data.last_name || null, data.phone, data.gender || null, data.dob || null, data.age || null, data.address || null]
  );
  return rows[0];
}

async function getPatientById(id) {
  const { rows } = await pool.query(`SELECT * FROM patients WHERE id = $1`, [id]);
  return rows[0] || null;
}

async function getPatientHistory(patientId) {
  const { rows } = await pool.query(
    `SELECT v.*, 
       (SELECT row_to_json(p) FROM (
          SELECT * FROM prescriptions WHERE visit_id = v.id ORDER BY created_at DESC LIMIT 1
       ) p) AS prescription,
       EXISTS(SELECT 1 FROM prescription_photos WHERE visit_id = v.id) AS has_photo_rx
     FROM visits v WHERE v.patient_id = $1 ORDER BY v.created_at DESC`,
    [patientId]
  );
  return rows;
}

// ============================= VISITS (Reception intake + Doctor queue) =============================
async function createVisit(patientId, vitals, createdBy) {
  const { rows } = await pool.query(
    `INSERT INTO visits (patient_id, bp, temperature, pulse, weight, chief_complaint, notes, status, created_by)
     VALUES ($1, $2, $3, $4, $5, $6, $7, 'waiting', $8) RETURNING *`,
    [patientId, vitals.bp || null, vitals.temperature || null, vitals.pulse || null, vitals.weight || null,
     vitals.chief_complaint || null, vitals.notes || null, createdBy]
  );
  return rows[0];
}

async function getDoctorQueue() {
  const { rows } = await pool.query(
    `SELECT v.*, p.first_name, p.last_name, p.phone, p.gender, p.age
     FROM visits v JOIN patients p ON p.id = v.patient_id
     WHERE v.status = 'waiting' ORDER BY v.created_at ASC`
  );
  return rows;
}

async function getVisitWithPatient(visitId) {
  const { rows } = await pool.query(
    `SELECT v.*, p.first_name, p.last_name, p.phone, p.gender, p.age, p.dob, p.address
     FROM visits v JOIN patients p ON p.id = v.patient_id WHERE v.id = $1`,
    [visitId]
  );
  return rows[0] || null;
}

async function updateVisitStatus(visitId, status, doctorId = null) {
  if (doctorId) {
    await pool.query(`UPDATE visits SET status = $1, doctor_id = $2 WHERE id = $3`, [status, doctorId, visitId]);
  } else {
    await pool.query(`UPDATE visits SET status = $1 WHERE id = $2`, [status, visitId]);
  }
  return getVisitWithPatient(visitId);
}

async function getBillingQueue() {
  const { rows } = await pool.query(
    `SELECT v.*, p.first_name, p.last_name, p.phone,
       su.username AS doctor_username, sp.full_name AS doctor_name
     FROM visits v
     JOIN patients p ON p.id = v.patient_id
     LEFT JOIN staff_users su ON su.id = v.doctor_id
     LEFT JOIN staff_profiles sp ON sp.staff_user_id = v.doctor_id
     WHERE v.status = 'ready_for_billing' ORDER BY v.created_at ASC`
  );
  return rows;
}

async function getDoctorStats(doctorId) {
  const today = new Date().toISOString().slice(0, 10);
  const queueQ = pool.query(`SELECT COUNT(*)::int AS c FROM visits WHERE status = 'waiting'`);
  const seenTodayQ = pool.query(
    `SELECT COUNT(*)::int AS c FROM visits WHERE doctor_id = $1 AND created_at::date = $2 AND status != 'waiting'`,
    [doctorId, today]
  );
  const totalSeenQ = pool.query(`SELECT COUNT(*)::int AS c FROM visits WHERE doctor_id = $1 AND status != 'waiting'`, [doctorId]);
  const [queue, seenToday, totalSeen] = await Promise.all([queueQ, seenTodayQ, totalSeenQ]);
  return { queueCount: queue.rows[0].c, seenToday: seenToday.rows[0].c, totalSeen: totalSeen.rows[0].c };
}

async function getBillingStats(staffId) {
  const today = new Date().toISOString().slice(0, 10);
  const pendingQ = pool.query(`SELECT COUNT(*)::int AS c FROM visits WHERE status = 'ready_for_billing'`);
  const billsTodayQ = pool.query(`SELECT COUNT(*)::int AS c FROM bills WHERE created_at::date = $1`, [today]);
  const revenueTodayQ = pool.query(`SELECT COALESCE(SUM(grand_total),0)::numeric(10,2) AS s FROM bills WHERE created_at::date = $1`, [today]);
  // total value of medicines billed today (per bill generation, not incl. consulting fee)
  const medicineRevenueTodayQ = pool.query(
    `SELECT COALESCE(SUM(bi.line_total),0)::numeric(10,2) AS s FROM bill_items bi
     JOIN bills b ON b.id = bi.bill_id WHERE b.created_at::date = $1`,
    [today]
  );
  const [pending, billsToday, revenueToday, medicineRevenueToday] = await Promise.all([pendingQ, billsTodayQ, revenueTodayQ, medicineRevenueTodayQ]);
  return {
    pendingCount: pending.rows[0].c,
    billsToday: billsToday.rows[0].c,
    revenueToday: revenueToday.rows[0].s,
    medicineRevenueToday: medicineRevenueToday.rows[0].s,
  };
}

// ============================= PRESCRIPTIONS =============================
async function createPrescription(visitId, doctorId, sections) {
  const { rows } = await pool.query(
    `INSERT INTO prescriptions
      (visit_id, doctor_id, mode, chief_complaint, examination, diagnosis, procedure_notes, advice,
       investigation, prognosis, findings, doctor_notes, emergency_instructions, follow_up)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,
    [
      visitId, doctorId, sections.mode || 'digital',
      sections.chief_complaint || null, sections.examination || null, sections.diagnosis || null,
      sections.procedure_notes || null, sections.advice || null, sections.investigation || null,
      sections.prognosis || null, sections.findings || null, sections.doctor_notes || null,
      sections.emergency_instructions || null, sections.follow_up || null,
    ]
  );
  return rows[0];
}

async function addPrescriptionMedicines(prescriptionId, medicines) {
  const inserted = [];
  for (const m of medicines) {
    const { rows } = await pool.query(
      `INSERT INTO prescription_medicines (prescription_id, medicine_id, medicine_name, dosage, instructions, quantity, price)
       VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`,
      [prescriptionId, m.medicine_id || null, m.medicine_name, m.dosage || null, m.instructions || null, m.quantity || 1, m.price || null]
    );
    inserted.push(rows[0]);
  }
  return inserted;
}

async function getPrescriptionByVisit(visitId) {
  const { rows } = await pool.query(
    `SELECT * FROM prescriptions WHERE visit_id = $1 ORDER BY created_at DESC LIMIT 1`,
    [visitId]
  );
  if (!rows[0]) return null;
  const prescription = rows[0];
  const { rows: meds } = await pool.query(
    `SELECT * FROM prescription_medicines WHERE prescription_id = $1`,
    [prescription.id]
  );
  prescription.medicines = meds;
  return prescription;
}

// ============================= MEDICINES (master list) =============================
async function searchMedicines(search) {
  const { rows } = await pool.query(
    `SELECT * FROM medicines WHERE active = true AND name ILIKE $1 ORDER BY name LIMIT 20`,
    [`%${search || ''}%`]
  );
  return rows;
}

async function listMedicines() {
  const { rows } = await pool.query(`SELECT * FROM medicines ORDER BY name`);
  return rows;
}

async function createMedicine(data) {
  const { rows } = await pool.query(
    `INSERT INTO medicines (name, strength, price, category, stock_quantity, low_stock_threshold, expiry_date)
     VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`,
    [
      data.name, data.strength || null, data.price || null, data.category || null,
      data.stock_quantity != null ? data.stock_quantity : null,
      data.low_stock_threshold || 10,
      data.expiry_date || null,
    ]
  );
  return rows[0];
}

async function updateMedicine(id, data) {
  await pool.query(
    `UPDATE medicines SET name=$1, strength=$2, price=$3, category=$4, active=$5,
       stock_quantity=$6, low_stock_threshold=$7, expiry_date=$8 WHERE id=$9`,
    [
      data.name, data.strength || null, data.price || null, data.category || null, data.active !== false,
      data.stock_quantity != null ? data.stock_quantity : null,
      data.low_stock_threshold || 10,
      data.expiry_date || null,
      id,
    ]
  );
  const { rows } = await pool.query(`SELECT * FROM medicines WHERE id = $1`, [id]);
  return rows[0];
}

// ============================= QUICK TYPE =============================
async function getQuickType(section) {
  const { rows } = await pool.query(
    `SELECT * FROM quick_type_suggestions WHERE section = $1 ORDER BY id`,
    [section]
  );
  return rows;
}

async function addQuickType(section, text, createdBy) {
  const { rows } = await pool.query(
    `INSERT INTO quick_type_suggestions (section, text, created_by) VALUES ($1,$2,$3) RETURNING *`,
    [section, text, createdBy]
  );
  return rows[0];
}

// ============================= BILLING =============================
function generateBillNumber() {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  const rand = Math.floor(1000 + Math.random() * 9000);
  return `BILL-${y}${m}${d}-${rand}`;
}

async function createBill(visitId, patientName, patientPhone, doctorName, items, discount, createdBy, consultingFee = 0) {
  const medicineSubtotal = items.reduce((sum, it) => sum + Number(it.unit_price), 0);
  const subtotal = medicineSubtotal + Number(consultingFee || 0);
  const grandTotal = Math.max(0, subtotal - (discount || 0));
  const billNumber = generateBillNumber();

  const { rows } = await pool.query(
    `INSERT INTO bills (visit_id, bill_number, patient_name, patient_phone, doctor_name, subtotal, discount, grand_total, created_by, consulting_fee)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,
    [visitId, billNumber, patientName, patientPhone, doctorName, subtotal, discount || 0, grandTotal, createdBy, consultingFee || 0]
  );
  const bill = rows[0];

  for (const it of items) {
    // homeopathic dispensing = one unit (tube/bottle) per line item, not a variable quantity
    await pool.query(
      `INSERT INTO bill_items (bill_id, medicine_id, medicine_name, quantity, unit_price, line_total)
       VALUES ($1,$2,$3,1,$4,$4)`,
      [bill.id, it.medicine_id || null, it.medicine_name, it.unit_price]
    );

    // auto-deduct inventory — one unit sold per line item
    if (it.medicine_id) {
      await pool.query(
        `UPDATE medicines SET stock_quantity = GREATEST(0, COALESCE(stock_quantity, 0) - 1) WHERE id = $1`,
        [it.medicine_id]
      );
    }
  }

  return getBillById(bill.id);
}

async function getBillById(id) {
  const { rows } = await pool.query(`SELECT * FROM bills WHERE id = $1`, [id]);
  if (!rows[0]) return null;
  const bill = rows[0];
  const { rows: items } = await pool.query(`SELECT * FROM bill_items WHERE bill_id = $1`, [id]);
  bill.items = items;
  return bill;
}

// ============================= CLINIC SETTINGS (consulting fee) =============================
async function getConsultingFee() {
  const { rows } = await pool.query(`SELECT value FROM clinic_settings WHERE key = 'consulting_fee'`);
  return rows[0] ? Number(rows[0].value) : 0;
}

async function setConsultingFee(amount) {
  await pool.query(
    `INSERT INTO clinic_settings (key, value, updated_at) VALUES ('consulting_fee', $1, now())
     ON CONFLICT (key) DO UPDATE SET value = $1, updated_at = now()`,
    [String(amount)]
  );
  return getConsultingFee();
}

// ============================= DATE RANGE HELPER =============================
function resolveDateRange(range, fromParam, toParam) {
  const now = new Date();
  const startOfDay = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate());
  let from, to;
  to = startOfDay(now);
  to.setDate(to.getDate() + 1); // exclusive upper bound = tomorrow 00:00

  switch (range) {
    case 'today':
      from = startOfDay(now);
      break;
    case 'yesterday':
      from = startOfDay(now); from.setDate(from.getDate() - 1);
      to = startOfDay(now);
      break;
    case 'this_week': {
      from = startOfDay(now); from.setDate(from.getDate() - from.getDay());
      break;
    }
    case 'this_month':
      from = new Date(now.getFullYear(), now.getMonth(), 1);
      break;
    case '3_months':
      from = new Date(now.getFullYear(), now.getMonth() - 3, now.getDate());
      break;
    case '6_months':
      from = new Date(now.getFullYear(), now.getMonth() - 6, now.getDate());
      break;
    case '1_year':
      from = new Date(now.getFullYear() - 1, now.getMonth(), now.getDate());
      break;
    case '2_years':
      from = new Date(now.getFullYear() - 2, now.getMonth(), now.getDate());
      break;
    case 'custom':
      from = fromParam ? new Date(fromParam) : startOfDay(now);
      to = toParam ? new Date(new Date(toParam).getTime() + 86400000) : to;
      break;
    default:
      from = startOfDay(now);
  }
  return { from: from.toISOString(), to: to.toISOString() };
}

// ============================= DOCTOR ANALYTICS =============================
async function getDoctorAnalytics(doctorId, range, fromParam, toParam) {
  const { from, to } = resolveDateRange(range, fromParam, toParam);

  const patientsQ = pool.query(
    `SELECT COUNT(*)::int AS c FROM visits WHERE doctor_id = $1 AND created_at >= $2 AND created_at < $3 AND status != 'waiting'`,
    [doctorId, from, to]
  );
  const consultingFeeQ = pool.query(
    `SELECT COALESCE(SUM(b.consulting_fee),0)::numeric(10,2) AS s FROM bills b
     JOIN visits v ON v.id = b.visit_id
     WHERE v.doctor_id = $1 AND b.created_at >= $2 AND b.created_at < $3`,
    [doctorId, from, to]
  );
  const medicineRevenueQ = pool.query(
    `SELECT COALESCE(SUM(bi.line_total),0)::numeric(10,2) AS s FROM bill_items bi
     JOIN bills b ON b.id = bi.bill_id
     JOIN visits v ON v.id = b.visit_id
     WHERE v.doctor_id = $1 AND b.created_at >= $2 AND b.created_at < $3`,
    [doctorId, from, to]
  );
  const medicinesSoldQ = pool.query(
    `SELECT COUNT(*)::int AS c FROM bill_items bi
     JOIN bills b ON b.id = bi.bill_id
     JOIN visits v ON v.id = b.visit_id
     WHERE v.doctor_id = $1 AND b.created_at >= $2 AND b.created_at < $3`,
    [doctorId, from, to]
  );
  const dailyQ = pool.query(
    `SELECT b.created_at::date AS day,
       COALESCE(SUM(bi.line_total),0)::numeric(10,2) AS medicine_revenue,
       COALESCE(MAX(b.consulting_fee),0)::numeric(10,2) AS fee_sample
     FROM bills b
     JOIN visits v ON v.id = b.visit_id
     LEFT JOIN bill_items bi ON bi.bill_id = b.id
     WHERE v.doctor_id = $1 AND b.created_at >= $2 AND b.created_at < $3
     GROUP BY b.created_at::date ORDER BY day`,
    [doctorId, from, to]
  );
  const dailyPatientsQ = pool.query(
    `SELECT created_at::date AS day, COUNT(*)::int AS c FROM visits
     WHERE doctor_id = $1 AND created_at >= $2 AND created_at < $3 AND status != 'waiting'
     GROUP BY created_at::date ORDER BY day`,
    [doctorId, from, to]
  );

  const topMedicinesQ = pool.query(
    `SELECT bi.medicine_name, COUNT(*)::int AS times_sold, COALESCE(SUM(bi.line_total),0)::numeric(10,2) AS revenue
     FROM bill_items bi
     JOIN bills b ON b.id = bi.bill_id
     JOIN visits v ON v.id = b.visit_id
     WHERE v.doctor_id = $1 AND b.created_at >= $2 AND b.created_at < $3
     GROUP BY bi.medicine_name ORDER BY revenue DESC LIMIT 8`,
    [doctorId, from, to]
  );

  const [patients, consultingFee, medicineRevenue, medicinesSold, daily, dailyPatients, topMedicines] = await Promise.all([
    patientsQ, consultingFeeQ, medicineRevenueQ, medicinesSoldQ, dailyQ, dailyPatientsQ, topMedicinesQ,
  ]);

  return {
    range: { from, to },
    patientCount: patients.rows[0].c,
    totalConsultingFee: consultingFee.rows[0].s,
    totalMedicineRevenue: medicineRevenue.rows[0].s,
    medicinesSold: medicinesSold.rows[0].c,
    totalRevenue: Number(consultingFee.rows[0].s) + Number(medicineRevenue.rows[0].s),
    dailyRevenue: daily.rows,
    dailyPatients: dailyPatients.rows,
    topMedicines: topMedicines.rows,
  };
}

// ============================= HISTORY (completed visits, kept forever) =============================
async function getDoctorHistory(doctorId, range, fromParam, toParam) {
  const { from, to } = resolveDateRange(range, fromParam, toParam);
  const { rows } = await pool.query(
    `SELECT v.*, p.first_name, p.last_name, p.phone
     FROM visits v JOIN patients p ON p.id = v.patient_id
     WHERE v.doctor_id = $1 AND v.status != 'waiting' AND v.created_at >= $2 AND v.created_at < $3
     ORDER BY v.created_at DESC`,
    [doctorId, from, to]
  );
  return rows;
}

async function getBillingHistory(range, fromParam, toParam) {
  const { from, to } = resolveDateRange(range, fromParam, toParam);
  const { rows } = await pool.query(
    `SELECT b.*, (SELECT COUNT(*)::int FROM bill_items WHERE bill_id = b.id) AS item_count
     FROM bills b WHERE b.created_at >= $1 AND b.created_at < $2 ORDER BY b.created_at DESC`,
    [from, to]
  );
  return rows;
}

// ============================= PHOTO RX =============================
async function savePrescriptionPhoto(visitId, buffer, mimeType, uploadedBy) {
  // one photo per visit — replace if one already exists
  await pool.query(`DELETE FROM prescription_photos WHERE visit_id = $1`, [visitId]);
  const { rows } = await pool.query(
    `INSERT INTO prescription_photos (visit_id, data, mime_type, uploaded_by) VALUES ($1,$2,$3,$4) RETURNING id, visit_id, mime_type, uploaded_at`,
    [visitId, buffer, mimeType, uploadedBy]
  );
  return rows[0];
}

async function getPrescriptionPhoto(visitId) {
  const { rows } = await pool.query(
    `SELECT data, mime_type, uploaded_at FROM prescription_photos WHERE visit_id = $1`,
    [visitId]
  );
  return rows[0] || null;
}

// ============================= PUBLIC BILL LOOKUP =============================
async function getBillByNumberAndPhone(billNumber, phone) {
  const { rows } = await pool.query(
    `SELECT * FROM bills WHERE bill_number = $1 AND patient_phone = $2`,
    [billNumber.trim().toUpperCase(), phone.trim()]
  );
  if (!rows[0]) return null;
  const bill = rows[0];
  const { rows: items } = await pool.query(`SELECT * FROM bill_items WHERE bill_id = $1`, [bill.id]);
  bill.items = items;
  return bill;
}

// Public, phone-only lookup — returns ALL bills for that phone number.
async function listBillsByPhone(phone) {
  const { rows } = await pool.query(
    `SELECT * FROM bills WHERE patient_phone = $1 ORDER BY created_at DESC`,
    [phone.trim()]
  );
  return rows;
}

// ============================= ATTACHMENTS =============================
async function addAttachment(visitId, filename, buffer, mimeType, uploadedBy) {
  const { rows } = await pool.query(
    `INSERT INTO visit_attachments (visit_id, filename, data, mime_type, uploaded_by)
     VALUES ($1,$2,$3,$4,$5) RETURNING id, visit_id, filename, mime_type, uploaded_at`,
    [visitId, filename, buffer, mimeType, uploadedBy]
  );
  return rows[0];
}

async function listAttachments(visitId) {
  const { rows } = await pool.query(
    `SELECT id, visit_id, filename, mime_type, uploaded_at FROM visit_attachments WHERE visit_id = $1 ORDER BY uploaded_at DESC`,
    [visitId]
  );
  return rows;
}

async function getAttachment(id) {
  const { rows } = await pool.query(`SELECT * FROM visit_attachments WHERE id = $1`, [id]);
  return rows[0] || null;
}

async function deleteAttachment(id) {
  await pool.query(`DELETE FROM visit_attachments WHERE id = $1`, [id]);
}

// ============================= AUDIT LOG =============================
async function logAudit(staffId, role, action, details) {
  try {
    await pool.query(
      `INSERT INTO audit_log (staff_id, role, action, details) VALUES ($1,$2,$3,$4)`,
      [staffId || null, role || null, action, details || null]
    );
  } catch (err) {
    console.error('Audit log failed (non-fatal):', err.message);
  }
}

async function getRecentAuditLog(limit = 100) {
  const { rows } = await pool.query(
    `SELECT al.*, su.username FROM audit_log al LEFT JOIN staff_users su ON su.id = al.staff_id
     ORDER BY al.created_at DESC LIMIT $1`,
    [limit]
  );
  return rows;
}

module.exports = {
  initClinicDb,
  pool,
  // staff
  getStaffByUsername, getStaffById, listStaff, createStaff, setStaffActive, deleteStaff,
  updateStaffProfile, updateStaffPhoto, getStaffPhoto,
  // clinic assets
  setClinicAsset, getClinicAsset,
  // patients
  findPatientsByPhone, searchPatients, createPatient, getPatientById, getPatientHistory,
  // visits
  createVisit, getDoctorQueue, getVisitWithPatient, updateVisitStatus, getBillingQueue,
  getDoctorStats, getBillingStats,
  // prescriptions
  createPrescription, addPrescriptionMedicines, getPrescriptionByVisit,
  // photo rx
  savePrescriptionPhoto, getPrescriptionPhoto,
  // medicines
  searchMedicines, listMedicines, createMedicine, updateMedicine,
  // quick type
  getQuickType, addQuickType,
  // billing
  createBill, getBillById, getBillByNumberAndPhone, listBillsByPhone,
  // settings
  getConsultingFee, setConsultingFee,
  // analytics & history
  getDoctorAnalytics, getDoctorHistory, getBillingHistory,
  // attachments
  addAttachment, listAttachments, getAttachment, deleteAttachment,
  // audit
  logAudit, getRecentAuditLog,
};
