// db/database.js
// -----------------------------------------------------------------------
// Uses PostgreSQL (via Supabase or any Postgres host) so data is permanent
// — it survives redeploys, restarts, and free-tier "ephemeral disk" resets
// that would otherwise wipe a local SQLite file.
//
// Requires DATABASE_URL in .env, e.g.:
//   postgresql://postgres:YOUR_PASSWORD@db.xxxx.supabase.co:5432/postgres
// -----------------------------------------------------------------------
const { Pool } = require('pg');

if (!process.env.DATABASE_URL) {
  console.error('\n❌ DATABASE_URL is not set in your .env file.');
  console.error('   Add your Supabase/Postgres connection string and restart.\n');
  process.exit(1);
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }, // required by Supabase
});

// ---- Schema (runs once at startup — safe to run every time, uses IF NOT EXISTS) ----
async function initDb() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS appointments (
      id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      appointment_code  TEXT UNIQUE NOT NULL,
      patient_name      TEXT NOT NULL,
      phone             TEXT NOT NULL,
      email             TEXT,
      age               INTEGER,
      gender            TEXT,
      concern           TEXT,
      preferred_date    TEXT NOT NULL,
      preferred_time    TEXT NOT NULL,
      status            TEXT NOT NULL DEFAULT 'pending',
      created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_appointments_date ON appointments(preferred_date);
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS reviews (
      id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      patient_name  TEXT NOT NULL,
      city          TEXT,
      rating        INTEGER NOT NULL DEFAULT 5,
      review_text   TEXT NOT NULL,
      source        TEXT NOT NULL DEFAULT 'patient_submitted',
      status        TEXT NOT NULL DEFAULT 'visible',
      created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
    );
  `);

  console.log('  ✓ Database schema ready (appointments, reviews)');
}

// ---- Helpers to generate a short, simple appointment code ----
const CODE_CHARS = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; // no 0,O,1,I,L

function generateCode(length = 6) {
  let code = '';
  for (let i = 0; i < length; i++) {
    code += CODE_CHARS[Math.floor(Math.random() * CODE_CHARS.length)];
  }
  return code;
}

async function nextAppointmentCode() {
  let code;
  let exists;
  do {
    code = generateCode();
    const { rows } = await pool.query(
      `SELECT 1 FROM appointments WHERE appointment_code = $1`,
      [code]
    );
    exists = rows.length > 0;
  } while (exists);
  return code;
}

// ---- Appointments CRUD ----
async function createAppointment(data) {
  const code = await nextAppointmentCode();
  const { rows } = await pool.query(
    `INSERT INTO appointments
      (appointment_code, patient_name, phone, email, age, gender, concern, preferred_date, preferred_time, status)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending')
     RETURNING *`,
    [
      code,
      data.patient_name,
      data.phone,
      data.email || null,
      data.age || null,
      data.gender || null,
      data.concern || null,
      data.preferred_date,
      data.preferred_time,
    ]
  );
  return rows[0];
}

async function getAppointmentById(id) {
  const { rows } = await pool.query(`SELECT * FROM appointments WHERE id = $1`, [id]);
  return rows[0] || null;
}

async function getAppointmentByCode(code) {
  const { rows } = await pool.query(
    `SELECT * FROM appointments WHERE appointment_code = $1`,
    [code]
  );
  return rows[0] || null;
}

async function listAppointments({ status, date, search } = {}) {
  let query = `SELECT * FROM appointments WHERE 1=1`;
  const params = [];

  if (status) {
    params.push(status);
    query += ` AND status = $${params.length}`;
  }
  if (date) {
    params.push(date);
    query += ` AND preferred_date = $${params.length}`;
  }
  if (search) {
    params.push(`%${search}%`);
    query += ` AND (patient_name ILIKE $${params.length} OR phone ILIKE $${params.length} OR appointment_code ILIKE $${params.length})`;
  }
  query += ` ORDER BY created_at DESC`;

  const { rows } = await pool.query(query, params);
  return rows;
}

async function updateAppointmentStatus(id, status) {
  await pool.query(`UPDATE appointments SET status = $1 WHERE id = $2`, [status, id]);
  return getAppointmentById(id);
}

async function getStats() {
  const totalQ = pool.query(`SELECT COUNT(*)::int AS c FROM appointments`);
  const pendingQ = pool.query(`SELECT COUNT(*)::int AS c FROM appointments WHERE status = 'pending'`);
  const confirmedQ = pool.query(`SELECT COUNT(*)::int AS c FROM appointments WHERE status = 'confirmed'`);
  const today = new Date().toISOString().slice(0, 10);
  const todayQ = pool.query(`SELECT COUNT(*)::int AS c FROM appointments WHERE preferred_date = $1`, [today]);

  const [total, pending, confirmed, todayCount] = await Promise.all([totalQ, pendingQ, confirmedQ, todayQ]);

  return {
    total: total.rows[0].c,
    pending: pending.rows[0].c,
    confirmed: confirmed.rows[0].c,
    todayCount: todayCount.rows[0].c,
  };
}

// ---- Reviews CRUD ----
async function createReview(data) {
  const { rows } = await pool.query(
    `INSERT INTO reviews (patient_name, city, rating, review_text, source, status)
     VALUES ($1, $2, $3, $4, $5, 'visible')
     RETURNING *`,
    [data.patient_name, data.city || null, data.rating, data.review_text, data.source || 'patient_submitted']
  );
  return rows[0];
}

async function getReviewById(id) {
  const { rows } = await pool.query(`SELECT * FROM reviews WHERE id = $1`, [id]);
  return rows[0] || null;
}

async function listVisibleReviews(limit = 20) {
  const { rows } = await pool.query(
    `SELECT * FROM reviews WHERE status = 'visible' ORDER BY created_at DESC LIMIT $1`,
    [limit]
  );
  return rows;
}

async function listAllReviews() {
  const { rows } = await pool.query(`SELECT * FROM reviews ORDER BY created_at DESC`);
  return rows;
}

async function updateReviewStatus(id, status) {
  await pool.query(`UPDATE reviews SET status = $1 WHERE id = $2`, [status, id]);
  return getReviewById(id);
}

async function deleteReview(id) {
  await pool.query(`DELETE FROM reviews WHERE id = $1`, [id]);
  return { deleted: true };
}

module.exports = {
  pool,
  initDb,
  createAppointment,
  getAppointmentById,
  getAppointmentByCode,
  listAppointments,
  updateAppointmentStatus,
  getStats,
  createReview,
  getReviewById,
  listVisibleReviews,
  listAllReviews,
  updateReviewStatus,
  deleteReview,
};
